# Generated by Django 4.1.6 on 2024-11-22 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrows',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 29, 23, 8, 7, 288435, tzinfo=datetime.timezone.utc)),
        ),
    ]
