# Generated by Django 4.1.6 on 2024-11-23 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_borrow_delete_borrows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 0, 39, 2, 124713, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='returned_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
