# Generated by Django 4.1.6 on 2024-12-10 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_borrow_due_date_alter_borrow_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='checkout_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 17, 3, 10, 45, 579435, tzinfo=datetime.timezone.utc)),
        ),
    ]
